apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: labs
  labels:
    app: vault
spec:
  containers:
  - name: vault
    image: vault:1.13.1
    ports:
    - containerPort: 8200

---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: labs
spec:
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
