apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  namespace: labs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: ifilyaninitmo/itdt-contained-frontend:master
        envFrom:
        - configMapRef:
            name: react-cfg
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react
  namespace: labs
spec:
  selector:
    app: react
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
